services:
  backend:
    build: .
    ports:
      - "8000:8000" # FastAPI
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - API_BASE_URL=http://localhost:8000/api/v1/agent-logs
    volumes:
      - ./app.db:/app/app.db
    restart: unless-stopped
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]

  frontend:
    build: .
    ports:
      - "8501:8501" # Streamlit
    environment:
      - API_BASE_URL=http://host.docker.internal:8000/api/v1/agent-logs
      - STREAMLIT_PORT=8501
    volumes:
      - ./app.db:/app/app.db
    restart: unless-stopped
    command:
      [
        "python",
        "-m",
        "streamlit",
        "run",
        "frontend/streamlit_app/app.py",
        "--server.port",
        "8501",
        "--server.address",
        "0.0.0.0",
        "--server.headless",
        "true",
      ]
    depends_on:
      - backend
