"""
core 패키지

핵심 설정 및 데이터 모델을 관리합니다.
"""

from src.core.config import (
    GEMINI_API_KEY,
    TAVILY_API_KEY,
    NOTION_API_KEY,
    DEFAULT_MODEL,
    MAX_MESSAGES,
    MAX_SEARCH_RESULTS,
    AVAILABLE_GEMINI_MODELS,
    WEB_SEARCH_AGENT_SYSTEM_MESSAGE,
    DATA_ANALYST_AGENT_SYSTEM_MESSAGE,
)

__all__ = [
    "GEMINI_API_KEY",
    "TAVILY_API_KEY",
    "NOTION_API_KEY",
    "DEFAULT_MODEL",
    "MAX_MESSAGES",
    "MAX_SEARCH_RESULTS",
    "AVAILABLE_GEMINI_MODELS",
    "WEB_SEARCH_AGENT_SYSTEM_MESSAGE",
    "DATA_ANALYST_AGENT_SYSTEM_MESSAGE",
]

